name: Reddit API Kenya

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  get_and_upload_reddit_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

    - name: Run your notebook
      run: |
        jupyter nbconvert --to notebook --execute reddit-api-scraper.ipynb --inplace
